#!/bin/bash
# AWS Configuration Setup Script
# Generated by NeoHarbour Security Configuration Helper

set -e

echo 'Setting up AWS resources for NeoHarbour Security...'

echo 'Fixing critical configuration issues...'

# KMS Key: alias/AsiaAgenticSoc
echo 'Setting up alias/AsiaAgenticSoc...'
sam build && sam deploy --guided

# Lambda Functions: Pipeline Functions
echo 'Setting up Pipeline Functions...'
sam build && sam deploy --guided

echo 'Fixing high priority configuration issues...'

echo 'AWS configuration setup complete!'
echo 'Run the validation script to verify: python tools/validate_aws_service_integration.py'